apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 11180
      targetPort: 11180
      protocol: TCP
      nodePort: 30080
    - name: https
      port: 11443
      targetPort: 11443
      protocol: TCP
      nodePort: 30443
